using System;


namespace F10Y.L0020
{
    /// <summary>
    /// Describes the result of running a command, including output lines, duration, and exit code.
    /// </summary>
    public class CommandResult
    {
        public string[] OutputLines { get; }
        public string[] ErrorLines { get; }
        public int ExitCode { get; }
        public TimeSpan Duration { get; }


        public CommandResult(
            string[] outputLines,
            string[] errorLines,
            int exitCode,
            TimeSpan duration)
        {
            this.OutputLines = outputLines;
            this.ErrorLines = errorLines;
            this.ExitCode = exitCode;
            this.Duration = duration;
        }
    }
}


namespace F10Y.L0020.N001
{
    /// <summary>
    /// A simplified version of <see cref="L0020.CommandResult"/>, lacking output lines generated by the command's execution (<see cref="L0020.CommandResult.OutputLines"/> and <see cref="L0020.CommandResult.ErrorLines"/>).
    /// </summary>
    public class CommandResult
    {
        public int ExitCode { get; }
        public TimeSpan Duration { get; }


        public CommandResult(
            int exitCode,
            TimeSpan duration)
        {
            this.ExitCode = exitCode;
            this.Duration = duration;
        }
    }
}
